spring:
  application:
    name: dihuan-ai-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dihuan_online_judge_system
    username: root
    password: root
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: sk-f3ec976dd1b64ba8aba22ecd6d774a61
      chat:
        options:
          model: deepseek-chat
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5-coder:1.5b


  cloud:
    sentinel:
      filter:
        enabled: true
      transport:
        dashboard: 127.0.0.1:8858
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
server:
  port: 8084
  servlet:
    context-path: /api/ai
#springdoc:
#  default-flat-param-object: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
knife4j:
  enable: true