spring:
  application:
    name: dihuan-user-service
  cloud:
    sentinel:
      filter:
        enabled: true
      transport:
        dashboard: localhost:8090
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dihuan_online_judge_system
    username: root
    password: thw20030806
server:
  port: 8082
  servlet:
    context-path: /api/user
#springdoc:
#  default-flat-param-object: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
knife4j:
  enable: true
